##./temp-plot.html is the file generated by genreport
from reportcs import genreport
from bottle import static_file, route, run, template, error



@route('/add')

#def main():

   #return template('index')



@route('/')

def send_static():
    genreport()
    return static_file("temp-plot.html", root='./')

run(host='0.0.0.0', port=8080)
